name: json_annotation
version: 4.8.1
description: >-
  Classes and helper functions that support JSON code generation via the
  `json_serializable` package.
repository: https://github.com/google/json_serializable.dart/tree/master/json_annotation
topics:
  - json
  - build-runner
  - json-serializable
  - codegen

environment:
  sdk: ^3.5.0

resolution: workspace

dependencies:
  meta: ^1.4.0
